spring.application.name=erp
server.port=8000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always