spring.datasource.url=jdbc:postgresql://cafe-erp-db.cfkywggekb28.eu-north-1.rds.amazonaws.com:5432/appdb
spring.datasource.username=postgres
spring.datasource.password=Suhassuppi9060

spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=false

logging.level.root=DEBUG
logging.level.com.cafe.erp=DEBUG
logging.level.org.springframework.web=DEBUG

server.error.include-message=never
server.error.include-stacktrace=never

management.metrics.export.prometheus.enabled=true

jwt.secret=VmRyJ0NlbHd5eG9yNTZyV3GtMjN4ZktOYW1rR25ES0pXS0RrTmVNVQ==